CREATE TABLE [dbo].[DimStore] (
    [StoreKey] INT     IDENTITY (1, 1) NOT NULL,
    [Store_id] TINYINT NULL,
    CONSTRAINT [PK__DimStore__ADC1E1AD2F8A0DCC] PRIMARY KEY CLUSTERED ([StoreKey] ASC)
);

