CREATE TABLE [dbo].[FactRental] (
    [RentalKey]           INT          IDENTITY (1, 1) NOT NULL,
    [Rental_id]           INT          NULL,
    [RentalDateKey]       INT          NULL,
    [ReturnDateKey]       INT          NULL,
    [RentalDuration]      TINYINT      NULL,
    [LoanPeriod]          TINYINT      NULL,
    [RentalRate]          DECIMAL (18) NULL,
    [FilmKey]             INT          NULL,
    [CustomerKey]         INT          NULL,
    [CustomerHistoryKey]  INT          NULL,
    [StaffKey]            INT          NULL,
    [UnitLanguageKey]     INT          NULL,
    [LanguageOfOriginKey] INT          NULL,
    [CategoryKey]         INT          NULL,
    [StoreKey]            INT          NULL,
    [PaymentAmount]       DECIMAL (18) CONSTRAINT [DF_FactRental_PaymentAmount] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__FactRent__9E152BD98C272AA3] PRIMARY KEY CLUSTERED ([RentalKey] ASC),
    CONSTRAINT [FK_FactRental.CategoryKey] FOREIGN KEY ([CategoryKey]) REFERENCES [dbo].[DimCategory] ([CategoryKey]),
    CONSTRAINT [FK_FactRental.CustomerHistoryKey] FOREIGN KEY ([CustomerHistoryKey]) REFERENCES [dbo].[DimCustomerHistory] ([CustomerHistoryKey]),
    CONSTRAINT [FK_FactRental.CustomerKey] FOREIGN KEY ([CustomerKey]) REFERENCES [dbo].[DimCustomer] ([CustomerKey]),
    CONSTRAINT [FK_FactRental.FilmKey] FOREIGN KEY ([FilmKey]) REFERENCES [dbo].[DimFilm] ([FilmKey]),
    CONSTRAINT [FK_FactRental.LanguageOfOriginKey] FOREIGN KEY ([LanguageOfOriginKey]) REFERENCES [dbo].[DimLanguage] ([LanguageKey]),
    CONSTRAINT [FK_FactRental.RentalDateKey] FOREIGN KEY ([RentalDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactRental.ReturnDateKey] FOREIGN KEY ([ReturnDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactRental.StaffKey] FOREIGN KEY ([StaffKey]) REFERENCES [dbo].[DimStaff] ([StaffKey]),
    CONSTRAINT [FK_FactRental.StoreKey] FOREIGN KEY ([StoreKey]) REFERENCES [dbo].[DimStore] ([StoreKey]),
    CONSTRAINT [FK_FactRental.UnitLanguageKey] FOREIGN KEY ([UnitLanguageKey]) REFERENCES [dbo].[DimLanguage] ([LanguageKey])
);

